export const SCORE_UPDATE_EVENT = 'SCORE_UPDATE_EVENT';

export const SPEED_UPDATE_EVENT = 'SPEED_UPDATE_EVENT';

export const ROWS_REMOVED_EVENT = 'ROWS_REMOVED_EVENT';

export const END_GAME_EVENT = 'END_GAME_EVENT';
